# Generated by Django 4.2.7 on 2023-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbeiro',
            name='barbearia',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='barbearia',
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.DeleteModel(
            name='Barbearia',
        ),
    ]
