# Generated by Django 4.2.7 on 2023-12-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentoapp', '0003_pedido_servico_alter_agendamento_servicos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido_servico',
            old_name='usuario',
            new_name='cliente',
        ),
    ]
