# Generated by Django 4.2.7 on 2023-12-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentoapp', '0004_rename_usuario_pedido_servico_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
