# Generated by Django 4.2.5 on 2023-12-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentoapp', '0006_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='barbeiro',
        ),
    ]
