# Generated by Django 4.2.5 on 2023-12-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentoapp', '0007_remove_feedback_barbeiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='status',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
